### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [milouse/quack#1]
This name is already taken on PyPI
https://pypi.org/project/quack/

**Comment by milouse** [comment]
Hi. Thank you for your interest in my helper.
I don't see it as a problem: I don't plan to add quack to pypi anytime soon, and if I do it, as it is a very specific software, it will be under a prefixed name like `archlinux-quack` or `quack-pkg` or `aur-quack`…

**Comment by jayvdb** [comment]
I'd love to be able to package this up for mingw/sys, which also uses pacman.  Packaging of Python typically expects the package name to be the PyPI name, to avoid name clashes and have a consistent naming convention.
